import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import ai, { MODELS } from '../../../../lib/gemini';
import { getSupabaseAdmin } from '../../../../lib/supabase';
import { Concept, SoundProfile, Song } from '../../../../lib/types';
import { nanoid } from 'nanoid';

export const maxDuration = 120; // Vercel timeout

export async function POST(req: NextRequest) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { lyria_prompt, concept, sound_profile } = body as { 
      lyria_prompt: string; 
      concept: Concept; 
      sound_profile: SoundProfile;
    };

    if (!lyria_prompt || !concept || !sound_profile) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const response = await ai.models.generateContent({
      model: MODELS.LYRIA,
      contents: lyria_prompt + "\n\nCreate a song between 2 minutes 45 seconds and 3 minutes long. Ensure you return the raw lyrics in the TEXT response modality.",
      config: {
        responseModalities: ["AUDIO", "TEXT"],
      },
    });

    let audioBuffer: Buffer | null = null;
    let lyrics = '';

    const candidate = response.candidates?.[0];
    if (candidate && candidate.content && candidate.content.parts) {
      for (const part of candidate.content.parts) {
        if (part.text) {
          lyrics += part.text + '\n';
        }
        if (part.inlineData && part.inlineData.mimeType?.startsWith('audio/') && part.inlineData.data) {
          audioBuffer = Buffer.from(part.inlineData.data, 'base64');
        }
      }
    }

    if (!audioBuffer) {
      return NextResponse.json({ error: 'No audio generated by the model' }, { status: 500 });
    }

    if (!lyrics.trim()) {
      return NextResponse.json({ error: 'No lyrics generated by the model' }, { status: 500 });
    }

    const songId = nanoid();
    const supabase = getSupabaseAdmin();

    const { error: uploadError } = await supabase.storage
      .from('audio')
      .upload(`${userId}/${songId}.mp3`, audioBuffer, {
        contentType: 'audio/mpeg',
        upsert: true,
      });

    if (uploadError) {
      console.error('Upload Error:', uploadError);
      return NextResponse.json({ error: 'Failed to upload audio' }, { status: 500 });
    }

    const { data: urlData } = supabase.storage.from('audio').getPublicUrl(`${userId}/${songId}.mp3`);
    const audioUrl = urlData.publicUrl;

    const newSong = {
      id: songId,
      user_id: userId,
      title: concept.title,
      genre: concept.genre,
      mood: concept.mood,
      bpm: concept.bpm,
      lyria_prompt: lyria_prompt,
      lyrics: lyrics.trim(),
      audio_url: audioUrl,
      status: 'ready',
      concept_json: concept,
      profile_snapshot: sound_profile,
      is_public: false,
      play_count: 0,
      resurface: false,
    };

    const { error: dbError } = await supabase
      .from('songs')
      .insert([newSong]);

    if (dbError) {
      console.error('Database Error:', dbError);
      return NextResponse.json({ error: 'Failed to save song metadata' }, { status: 500 });
    }

    return NextResponse.json({ song: newSong });

  } catch (error) {
    console.error('Error generating music:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
