import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import ai, { MODELS } from '@/lib/gemini';
import { getSupabaseAdmin } from '@/lib/supabase';
import { Concept } from '@/lib/types';

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { song_id, concept } = body as { song_id: string; concept: Concept };

    if (!song_id || !concept) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const coverPrompt = `Album cover art for "${concept.title}", a ${concept.genre} track. ${concept.mood} atmosphere.
Minimal, editorial. Black and white with one accent color.
No faces. No text. Square format.
Style: abstract, modern, influenced by ${concept.genre} aesthetics`;

    const response = await ai.models.generateContent({
      model: MODELS.NANO_BANANA,
      contents: coverPrompt,
    });

    let imageBuffer: Buffer | null = null;
    let contentType = 'image/jpeg';
    let extension = 'jpg';

    const candidate = response.candidates?.[0];
    if (candidate && candidate.content && candidate.content.parts) {
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.mimeType?.startsWith('image/') && part.inlineData.data) {
          imageBuffer = Buffer.from(part.inlineData.data, 'base64');
          contentType = part.inlineData.mimeType;
          extension = contentType.split('/')[1] || 'jpg';
        }
      }
    }

    if (!imageBuffer) {
      return NextResponse.json({ error: 'No image generated by the model' }, { status: 500 });
    }

    const supabase = getSupabaseAdmin();
    const storagePath = `${userId}/${song_id}.${extension}`;

    const { error: uploadError } = await supabase.storage
      .from('covers')
      .upload(storagePath, imageBuffer, {
        contentType: contentType,
        upsert: true,
      });

    if (uploadError) {
      console.error('Upload Error:', uploadError);
      return NextResponse.json({ error: 'Failed to upload cover art' }, { status: 500 });
    }

    const { data: urlData } = supabase.storage.from('covers').getPublicUrl(storagePath);
    const coverUrl = urlData.publicUrl;

    const { error: dbError } = await supabase
      .from('songs')
      .update({ cover_url: coverUrl })
      .eq('id', song_id)
      .eq('user_id', userId);

    if (dbError) {
      console.error('Database Error:', dbError);
      return NextResponse.json({ error: 'Failed to update song metadata' }, { status: 500 });
    }

    return NextResponse.json({ cover_url: coverUrl });

  } catch (error) {
    console.error('Error generating cover art:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
